panda:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000   
  
  # Effort Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint1
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint2
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint3
  joint4_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint4
  joint5_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint5
  joint6_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint6
  joint7_effort_controller:
    type: effort_controllers/JointEffortController
    joint: panda_joint7
  # joint_leftfinger_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: panda_finger_joint1
  # joint_rightfinger_effort_controller:
  #   type: effort_controllers/JointEffortController
  #   joint: panda_finger_joint2
  
  # Postion Controllers ----------------------------------------
  joint_leftfinger_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint1
    pid: {p: 5, i: 0, d: 3, i_clamp: 1}
  joint_rightfinger_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint2
    pid: {p: 5, i: 0, d: 3, i_clamp: 1}