panda:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint1
    pid: {p: 120.0, i: 0.0, d: 20.0, i_clamp: 2.5}
    # pid: {p: 12000.0, i: 0.0, d: 50, i_clamp: 10000}
  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint2
    # pid: {p: 300.0, i: 0.0, d: 20.0, i_clamp: 4.0}
    pid: {p: 30000, i: 0.02, d: 100, i_clamp: 10000 }
  joint3_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint3
    pid: {p: 180.0, i: 0.0, d: 20.0, i_clamp: 2.5}
    # pid: {p: 18000.0, i: 0.01, d: 50, i_clamp: 1}
  joint4_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint4
    # pid: {p: 180.0, i: 0.0, d: 20.0, i_clamp: 2.5}
    pid: {p: 18000, i: 0.01, d: 70, i_clamp: 10000 }
  joint5_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint5
    # pid: {p: 70.0, i: 0.0, d: 4.0, i_clamp: 1.0}
    pid: {p: 12000.0, i: 0.01, d: 70, i_clamp: 1}
  joint6_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint6
    # pid: {p: 20.0, i: 0.0, d: 3.0, i_clamp: 1.0}
    pid: {p: 7000, i: 0.01, d: 50, i_clamp: 1 }
  joint7_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: panda_joint7
    # pid: {p: 20.0, i: 0.0, d: 4.0, i_clamp: 1.0}
    pid: {p: 2000, i: 0.0, d: 20, i_clamp: 1}
  # joint_leftfinger_position_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: panda_finger_joint1
  #   pid: {p: 5, i: 0, d: 3, i_clamp: 1}
  # joint_rightfinger_position_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: panda_finger_joint2
  #   pid: {p: 5, i: 0, d: 3, i_clamp: 1}
  
  panda_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - panda_finger_joint1
    gains:
      panda_finger_joint1 : {p: 10000, i: 0, d: 3, i_clamp: 1}

    constraints:
      goal_time: 2.0
      stopped_position_tolerance: 0
      stopped_velocity_tolerance: 0
    
    state_publish_rate: 100
  
  joint_rightfinger_position_controller:
    type: effort_controllers/JointPositionController
    joint: panda_finger_joint2
    pid: {p: 5, i: 0, d: 3, i_clamp: 1}