// Generated by gencpp from file rl_interface/PandaCmd.msg
// DO NOT EDIT!


#ifndef RL_INTERFACE_MESSAGE_PANDACMD_H
#define RL_INTERFACE_MESSAGE_PANDACMD_H

#include <ros/service_traits.h>


#include <rl_interface/PandaCmdRequest.h>
#include <rl_interface/PandaCmdResponse.h>


namespace rl_interface
{

struct PandaCmd
{

typedef PandaCmdRequest Request;
typedef PandaCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PandaCmd
} // namespace rl_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rl_interface::PandaCmd > {
  static const char* value()
  {
    return "c1a7b32be5be6c0f024512355d194266";
  }

  static const char* value(const ::rl_interface::PandaCmd&) { return value(); }
};

template<>
struct DataType< ::rl_interface::PandaCmd > {
  static const char* value()
  {
    return "rl_interface/PandaCmd";
  }

  static const char* value(const ::rl_interface::PandaCmd&) { return value(); }
};


// service_traits::MD5Sum< ::rl_interface::PandaCmdRequest> should match
// service_traits::MD5Sum< ::rl_interface::PandaCmd >
template<>
struct MD5Sum< ::rl_interface::PandaCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rl_interface::PandaCmd >::value();
  }
  static const char* value(const ::rl_interface::PandaCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_interface::PandaCmdRequest> should match
// service_traits::DataType< ::rl_interface::PandaCmd >
template<>
struct DataType< ::rl_interface::PandaCmdRequest>
{
  static const char* value()
  {
    return DataType< ::rl_interface::PandaCmd >::value();
  }
  static const char* value(const ::rl_interface::PandaCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rl_interface::PandaCmdResponse> should match
// service_traits::MD5Sum< ::rl_interface::PandaCmd >
template<>
struct MD5Sum< ::rl_interface::PandaCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rl_interface::PandaCmd >::value();
  }
  static const char* value(const ::rl_interface::PandaCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rl_interface::PandaCmdResponse> should match
// service_traits::DataType< ::rl_interface::PandaCmd >
template<>
struct DataType< ::rl_interface::PandaCmdResponse>
{
  static const char* value()
  {
    return DataType< ::rl_interface::PandaCmd >::value();
  }
  static const char* value(const ::rl_interface::PandaCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RL_INTERFACE_MESSAGE_PANDACMD_H
