// Generated by gencpp from file rl_interface/PandaCmdResponse.msg
// DO NOT EDIT!


#ifndef RL_INTERFACE_MESSAGE_PANDACMDRESPONSE_H
#define RL_INTERFACE_MESSAGE_PANDACMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace rl_interface
{
template <class ContainerAllocator>
struct PandaCmdResponse_
{
  typedef PandaCmdResponse_<ContainerAllocator> Type;

  PandaCmdResponse_()
    : success()  {
    }
  PandaCmdResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::rl_interface::PandaCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_interface::PandaCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PandaCmdResponse_

typedef ::rl_interface::PandaCmdResponse_<std::allocator<void> > PandaCmdResponse;

typedef boost::shared_ptr< ::rl_interface::PandaCmdResponse > PandaCmdResponsePtr;
typedef boost::shared_ptr< ::rl_interface::PandaCmdResponse const> PandaCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_interface::PandaCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_interface::PandaCmdResponse_<ContainerAllocator1> & lhs, const ::rl_interface::PandaCmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_interface::PandaCmdResponse_<ContainerAllocator1> & lhs, const ::rl_interface::PandaCmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_interface::PandaCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_interface::PandaCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_interface::PandaCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::rl_interface::PandaCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_interface/PandaCmdResponse";
  }

  static const char* value(const ::rl_interface::PandaCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::rl_interface::PandaCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PandaCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_interface::PandaCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_interface::PandaCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_INTERFACE_MESSAGE_PANDACMDRESPONSE_H
