// Generated by gencpp from file rl_interface/PandaCmdRequest.msg
// DO NOT EDIT!


#ifndef RL_INTERFACE_MESSAGE_PANDACMDREQUEST_H
#define RL_INTERFACE_MESSAGE_PANDACMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace rl_interface
{
template <class ContainerAllocator>
struct PandaCmdRequest_
{
  typedef PandaCmdRequest_<ContainerAllocator> Type;

  PandaCmdRequest_()
    : cmd()  {
    }
  PandaCmdRequest_(const ContainerAllocator& _alloc)
    : cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;





  typedef boost::shared_ptr< ::rl_interface::PandaCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rl_interface::PandaCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PandaCmdRequest_

typedef ::rl_interface::PandaCmdRequest_<std::allocator<void> > PandaCmdRequest;

typedef boost::shared_ptr< ::rl_interface::PandaCmdRequest > PandaCmdRequestPtr;
typedef boost::shared_ptr< ::rl_interface::PandaCmdRequest const> PandaCmdRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rl_interface::PandaCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rl_interface::PandaCmdRequest_<ContainerAllocator1> & lhs, const ::rl_interface::PandaCmdRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rl_interface::PandaCmdRequest_<ContainerAllocator1> & lhs, const ::rl_interface::PandaCmdRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rl_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rl_interface::PandaCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rl_interface::PandaCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rl_interface::PandaCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71560d7d8cfa9873c3906c0a0eb3188b";
  }

  static const char* value(const ::rl_interface::PandaCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71560d7d8cfa9873ULL;
  static const uint64_t static_value2 = 0xc3906c0a0eb3188bULL;
};

template<class ContainerAllocator>
struct DataType< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rl_interface/PandaCmdRequest";
  }

  static const char* value(const ::rl_interface::PandaCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray cmd\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::rl_interface::PandaCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PandaCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rl_interface::PandaCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rl_interface::PandaCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RL_INTERFACE_MESSAGE_PANDACMDREQUEST_H
