; Auto-generated. Do not edit!


(cl:in-package path_navigation_msgs-msg)


;//! \htmlinclude PathExecutionFeedback.msg.html

(cl:defclass <PathExecutionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PathExecutionFeedback (<PathExecutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PathExecutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PathExecutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name path_navigation_msgs-msg:<PathExecutionFeedback> is deprecated: use path_navigation_msgs-msg:PathExecutionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PathExecutionFeedback>) ostream)
  "Serializes a message object of type '<PathExecutionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PathExecutionFeedback>) istream)
  "Deserializes a message object of type '<PathExecutionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PathExecutionFeedback>)))
  "Returns string type for a message object of type '<PathExecutionFeedback>"
  "path_navigation_msgs/PathExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PathExecutionFeedback)))
  "Returns string type for a message object of type 'PathExecutionFeedback"
  "path_navigation_msgs/PathExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PathExecutionFeedback>)))
  "Returns md5sum for a message object of type '<PathExecutionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PathExecutionFeedback)))
  "Returns md5sum for a message object of type 'PathExecutionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PathExecutionFeedback>)))
  "Returns full string definition for message of type '<PathExecutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PathExecutionFeedback)))
  "Returns full string definition for message of type 'PathExecutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PathExecutionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PathExecutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PathExecutionFeedback
))
