; Auto-generated. Do not edit!


(cl:in-package path_navigation_msgs-msg)


;//! \htmlinclude TransformPathExecutionFeedback.msg.html

(cl:defclass <TransformPathExecutionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass TransformPathExecutionFeedback (<TransformPathExecutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TransformPathExecutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TransformPathExecutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name path_navigation_msgs-msg:<TransformPathExecutionFeedback> is deprecated: use path_navigation_msgs-msg:TransformPathExecutionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TransformPathExecutionFeedback>) ostream)
  "Serializes a message object of type '<TransformPathExecutionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TransformPathExecutionFeedback>) istream)
  "Deserializes a message object of type '<TransformPathExecutionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TransformPathExecutionFeedback>)))
  "Returns string type for a message object of type '<TransformPathExecutionFeedback>"
  "path_navigation_msgs/TransformPathExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TransformPathExecutionFeedback)))
  "Returns string type for a message object of type 'TransformPathExecutionFeedback"
  "path_navigation_msgs/TransformPathExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TransformPathExecutionFeedback>)))
  "Returns md5sum for a message object of type '<TransformPathExecutionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TransformPathExecutionFeedback)))
  "Returns md5sum for a message object of type 'TransformPathExecutionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TransformPathExecutionFeedback>)))
  "Returns full string definition for message of type '<TransformPathExecutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TransformPathExecutionFeedback)))
  "Returns full string definition for message of type 'TransformPathExecutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TransformPathExecutionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TransformPathExecutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TransformPathExecutionFeedback
))
