// Generated by gencpp from file gazebo_test_tools/RecognizeGazeboObjectResponse.msg
// DO NOT EDIT!


#ifndef GAZEBO_TEST_TOOLS_MESSAGE_RECOGNIZEGAZEBOOBJECTRESPONSE_H
#define GAZEBO_TEST_TOOLS_MESSAGE_RECOGNIZEGAZEBOOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_test_tools
{
template <class ContainerAllocator>
struct RecognizeGazeboObjectResponse_
{
  typedef RecognizeGazeboObjectResponse_<ContainerAllocator> Type;

  RecognizeGazeboObjectResponse_()
    : success(false)  {
    }
  RecognizeGazeboObjectResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RecognizeGazeboObjectResponse_

typedef ::gazebo_test_tools::RecognizeGazeboObjectResponse_<std::allocator<void> > RecognizeGazeboObjectResponse;

typedef boost::shared_ptr< ::gazebo_test_tools::RecognizeGazeboObjectResponse > RecognizeGazeboObjectResponsePtr;
typedef boost::shared_ptr< ::gazebo_test_tools::RecognizeGazeboObjectResponse const> RecognizeGazeboObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator1> & lhs, const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator1> & lhs, const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_test_tools

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_test_tools/RecognizeGazeboObjectResponse";
  }

  static const char* value(const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# If true, found the object in Gazebo and published the message.\n"
"bool success\n"
"\n"
;
  }

  static const char* value(const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognizeGazeboObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_test_tools::RecognizeGazeboObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_TEST_TOOLS_MESSAGE_RECOGNIZEGAZEBOOBJECTRESPONSE_H
