(cl:defpackage gazebo_test_tools-srv
  (:use )
  (:export
   "RECOGNIZEGAZEBOOBJECT"
   "<RECOGNIZEGAZEBOOBJECT-REQUEST>"
   "RECOGNIZEGAZEBOOBJECT-REQUEST"
   "<RECOGNIZEGAZEBOOBJECT-RESPONSE>"
   "RECOGNIZEGAZEBOOBJECT-RESPONSE"
  ))

