// Generated by gencpp from file panda_state/RobotStates.msg
// DO NOT EDIT!


#ifndef PANDA_STATE_MESSAGE_ROBOTSTATES_H
#define PANDA_STATE_MESSAGE_ROBOTSTATES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float64.h>

namespace panda_state
{
template <class ContainerAllocator>
struct RobotStates_
{
  typedef RobotStates_<ContainerAllocator> Type;

  RobotStates_()
    : header()
    , xe()  {
    }
  RobotStates_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , xe()  {
  (void)_alloc;
      xe.assign( ::std_msgs::Float64_<ContainerAllocator> (_alloc));
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array< ::std_msgs::Float64_<ContainerAllocator> , 3>  _xe_type;
  _xe_type xe;





  typedef boost::shared_ptr< ::panda_state::RobotStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::panda_state::RobotStates_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStates_

typedef ::panda_state::RobotStates_<std::allocator<void> > RobotStates;

typedef boost::shared_ptr< ::panda_state::RobotStates > RobotStatesPtr;
typedef boost::shared_ptr< ::panda_state::RobotStates const> RobotStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::panda_state::RobotStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::panda_state::RobotStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::panda_state::RobotStates_<ContainerAllocator1> & lhs, const ::panda_state::RobotStates_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.xe == rhs.xe;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::panda_state::RobotStates_<ContainerAllocator1> & lhs, const ::panda_state::RobotStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace panda_state

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::panda_state::RobotStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::panda_state::RobotStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_state::RobotStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::panda_state::RobotStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_state::RobotStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::panda_state::RobotStates_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::panda_state::RobotStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79c455d062acdbc2bbc3010df721a4d4";
  }

  static const char* value(const ::panda_state::RobotStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79c455d062acdbc2ULL;
  static const uint64_t static_value2 = 0xbbc3010df721a4d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::panda_state::RobotStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "panda_state/RobotStates";
  }

  static const char* value(const ::panda_state::RobotStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::panda_state::RobotStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"std_msgs/Float64[3] xe \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::panda_state::RobotStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::panda_state::RobotStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.xe);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::panda_state::RobotStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::panda_state::RobotStates_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "xe[]" << std::endl;
    for (size_t i = 0; i < v.xe.size(); ++i)
    {
      s << indent << "  xe[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "    ", v.xe[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PANDA_STATE_MESSAGE_ROBOTSTATES_H
