// Generated by gencpp from file path_navigation_msgs/PathExecutionResult.msg
// DO NOT EDIT!


#ifndef PATH_NAVIGATION_MSGS_MESSAGE_PATHEXECUTIONRESULT_H
#define PATH_NAVIGATION_MSGS_MESSAGE_PATHEXECUTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseWithCovarianceStamped.h>

namespace path_navigation_msgs
{
template <class ContainerAllocator>
struct PathExecutionResult_
{
  typedef PathExecutionResult_<ContainerAllocator> Type;

  PathExecutionResult_()
    : finalpose()  {
    }
  PathExecutionResult_(const ContainerAllocator& _alloc)
    : finalpose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator>  _finalpose_type;
  _finalpose_type finalpose;





  typedef boost::shared_ptr< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> const> ConstPtr;

}; // struct PathExecutionResult_

typedef ::path_navigation_msgs::PathExecutionResult_<std::allocator<void> > PathExecutionResult;

typedef boost::shared_ptr< ::path_navigation_msgs::PathExecutionResult > PathExecutionResultPtr;
typedef boost::shared_ptr< ::path_navigation_msgs::PathExecutionResult const> PathExecutionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator1> & lhs, const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator2> & rhs)
{
  return lhs.finalpose == rhs.finalpose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator1> & lhs, const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace path_navigation_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de191de1f3cf450e599cc31709760e6";
  }

  static const char* value(const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de191de1f3cf450ULL;
  static const uint64_t static_value2 = 0xe599cc31709760e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_navigation_msgs/PathExecutionResult";
  }

  static const char* value(const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# The actual end pose when robot has navigated.\n"
"geometry_msgs/PoseWithCovarianceStamped finalpose\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovarianceStamped\n"
"# This expresses an estimated pose with a reference coordinate frame and timestamp\n"
"\n"
"Header header\n"
"PoseWithCovariance pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finalpose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathExecutionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_navigation_msgs::PathExecutionResult_<ContainerAllocator>& v)
  {
    s << indent << "finalpose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.finalpose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_NAVIGATION_MSGS_MESSAGE_PATHEXECUTIONRESULT_H
