// Generated by gencpp from file scene_objects/AddObjectsResponse.msg
// DO NOT EDIT!


#ifndef SCENE_OBJECTS_MESSAGE_ADDOBJECTSRESPONSE_H
#define SCENE_OBJECTS_MESSAGE_ADDOBJECTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace scene_objects
{
template <class ContainerAllocator>
struct AddObjectsResponse_
{
  typedef AddObjectsResponse_<ContainerAllocator> Type;

  AddObjectsResponse_()
    : success()  {
    }
  AddObjectsResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::scene_objects::AddObjectsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scene_objects::AddObjectsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddObjectsResponse_

typedef ::scene_objects::AddObjectsResponse_<std::allocator<void> > AddObjectsResponse;

typedef boost::shared_ptr< ::scene_objects::AddObjectsResponse > AddObjectsResponsePtr;
typedef boost::shared_ptr< ::scene_objects::AddObjectsResponse const> AddObjectsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scene_objects::AddObjectsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::scene_objects::AddObjectsResponse_<ContainerAllocator1> & lhs, const ::scene_objects::AddObjectsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::scene_objects::AddObjectsResponse_<ContainerAllocator1> & lhs, const ::scene_objects::AddObjectsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace scene_objects

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scene_objects::AddObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scene_objects::AddObjectsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scene_objects::AddObjectsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::scene_objects::AddObjectsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scene_objects/AddObjectsResponse";
  }

  static const char* value(const ::scene_objects::AddObjectsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool success\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::scene_objects::AddObjectsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddObjectsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scene_objects::AddObjectsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scene_objects::AddObjectsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCENE_OBJECTS_MESSAGE_ADDOBJECTSRESPONSE_H
