(cl:defpackage object_msgs-srv
  (:use )
  (:export
   "OBJECTINFO"
   "<OBJECTINFO-REQUEST>"
   "OBJECTINFO-REQUEST"
   "<OBJECTINFO-RESPONSE>"
   "OBJECTINFO-RESPONSE"
   "REGISTEROBJECT"
   "<REGISTEROBJECT-REQUEST>"
   "REGISTEROBJECT-REQUEST"
   "<REGISTEROBJECT-RESPONSE>"
   "REGISTEROBJECT-RESPONSE"
  ))

