// Generated by gencpp from file object_msgs/ObjectInfo.msg
// DO NOT EDIT!


#ifndef OBJECT_MSGS_MESSAGE_OBJECTINFO_H
#define OBJECT_MSGS_MESSAGE_OBJECTINFO_H

#include <ros/service_traits.h>


#include <object_msgs/ObjectInfoRequest.h>
#include <object_msgs/ObjectInfoResponse.h>


namespace object_msgs
{

struct ObjectInfo
{

typedef ObjectInfoRequest Request;
typedef ObjectInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ObjectInfo
} // namespace object_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_msgs::ObjectInfo > {
  static const char* value()
  {
    return "914392dfee158e8d82269f3dc686d92b";
  }

  static const char* value(const ::object_msgs::ObjectInfo&) { return value(); }
};

template<>
struct DataType< ::object_msgs::ObjectInfo > {
  static const char* value()
  {
    return "object_msgs/ObjectInfo";
  }

  static const char* value(const ::object_msgs::ObjectInfo&) { return value(); }
};


// service_traits::MD5Sum< ::object_msgs::ObjectInfoRequest> should match
// service_traits::MD5Sum< ::object_msgs::ObjectInfo >
template<>
struct MD5Sum< ::object_msgs::ObjectInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::ObjectInfo >::value();
  }
  static const char* value(const ::object_msgs::ObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::ObjectInfoRequest> should match
// service_traits::DataType< ::object_msgs::ObjectInfo >
template<>
struct DataType< ::object_msgs::ObjectInfoRequest>
{
  static const char* value()
  {
    return DataType< ::object_msgs::ObjectInfo >::value();
  }
  static const char* value(const ::object_msgs::ObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_msgs::ObjectInfoResponse> should match
// service_traits::MD5Sum< ::object_msgs::ObjectInfo >
template<>
struct MD5Sum< ::object_msgs::ObjectInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_msgs::ObjectInfo >::value();
  }
  static const char* value(const ::object_msgs::ObjectInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_msgs::ObjectInfoResponse> should match
// service_traits::DataType< ::object_msgs::ObjectInfo >
template<>
struct DataType< ::object_msgs::ObjectInfoResponse>
{
  static const char* value()
  {
    return DataType< ::object_msgs::ObjectInfo >::value();
  }
  static const char* value(const ::object_msgs::ObjectInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_MSGS_MESSAGE_OBJECTINFO_H
